# Generated by Django 4.2.9 on 2025-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('from_date', models.CharField(max_length=255)),
                ('to_date', models.CharField(max_length=255)),
                ('prohibited_practice', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('idb_sanction_type', models.CharField(max_length=255)),
                ('idb_sanction_source', models.CharField(max_length=255)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
