# Generated by Django 4.2.9 on 2025-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionedentity',
            name='from_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sanctionedentity',
            name='other_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sanctionedentity',
            name='prohibited_practice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sanctionedentity',
            name='to_date',
            field=models.CharField(max_length=100),
        ),
    ]
