# Generated by Django 4.2.9 on 2025-03-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_alter_sanctionedentity_from_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=255, verbose_name='Entidad')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=100, unique=True, verbose_name='Número de Documento')),
                ('nombre_infractor', models.CharField(max_length=255, verbose_name='Nombre del Infractor')),
                ('autoridad', models.CharField(max_length=255, verbose_name='Autoridad Ambiental')),
                ('acto', models.CharField(max_length=255, verbose_name='Acto Administrativo')),
                ('fecha_acto', models.CharField(max_length=100, verbose_name='Fecha del Acto')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
    ]
