# Generated by Django 4.2.9 on 2025-03-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_environmentalsanction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServidorPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('entidad', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
    ]
