# Generated by Django 4.2.9 on 2025-03-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0004_servidorpublico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidorpublico',
            name='correo',
        ),
        migrations.AlterField(
            model_name='servidorpublico',
            name='cargo',
            field=models.CharField(default='No especificado', max_length=200),
        ),
        migrations.AlterField(
            model_name='servidorpublico',
            name='entidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servidorpublico',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servidorpublico',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servidorpublico',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
