# Generated by Django 4.2.9 on 2025-03-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0005_remove_servidorpublico_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidorpublico',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='servidorpublico',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='servidorpublico',
            name='estado',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='servidorpublico',
            name='nivel',
            field=models.CharField(default='No definido', max_length=100),
        ),
        migrations.AlterField(
            model_name='servidorpublico',
            name='cargo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servidorpublico',
            name='entidad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servidorpublico',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
