# Generated by Django 4.2.9 on 2025-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0006_remove_servidorpublico_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaNoAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('razon', models.TextField(blank=True, null=True)),
                ('fecha', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
