# Generated by Django 4.2.9 on 2025-05-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0007_empresanoautorizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fugitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_captura', models.DateField(verbose_name='Fecha de Captura')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('cargos', models.TextField(blank=True, verbose_name='Cargos')),
                ('raza', models.CharField(blank=True, max_length=50, verbose_name='Raza')),
                ('sexo', models.CharField(blank=True, max_length=20, verbose_name='Sexo')),
                ('estatura', models.CharField(blank=True, max_length=20, verbose_name='Estatura')),
                ('peso', models.CharField(blank=True, max_length=20, verbose_name='Peso')),
                ('color_cabello', models.CharField(blank=True, max_length=50, verbose_name='Color de Cabello')),
                ('color_ojos', models.CharField(blank=True, max_length=50, verbose_name='Color de Ojos')),
                ('ano_nacimiento', models.CharField(blank=True, max_length=10, verbose_name='Año de Nacimiento')),
                ('ncic', models.CharField(blank=True, max_length=50, verbose_name='NCIC #')),
                ('jurisdiccion', models.CharField(blank=True, max_length=255, verbose_name='Jurisdicción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL de Perfil')),
            ],
        ),
    ]
